questions = [
    {
        "type": "input",
        "name": "first_name",
        "message": "What is the targets first name",
    },
    {
        "type": "input",
        "name": "last_name",
        "message": "What is the targets last name",
    },
    {
        "type": "input",
        "name": "birthday",
        "message": "What is the targets birthday (DD/MM/YYYY)",
    },
]

characterswap = {
    "A": ["4"],
    "a": ["4"],
    "C": ["(", "[", "{"],
    "c": ["(", "[", "{"],
    "E": ["€", "3"],
    "e": ["€", "3"],
    "G": ["&"],
    "g": ["&"],
    "I": ["1", "!", "l", "|", "L"],
    "i": ["1", "!", "l", "|", "L"],
    "L": ["I", "!", "1", "i", "|"],
    "l": ["I", "!", "1", "i", "|"],
    "O": ["0", "°", "Q", "q"],
    "o": ["0", "°", "Q", "q"],
    "Q": ["@"],
    "q": ["@"],
    "S": ["$", "Z", "z"],
    "s": ["$", "Z", "z"],
    "X": ["*", "+"],
    "x": ["*", "+"],
    "Z": ["s", "$"],
    "z": ["s", "$"],
    "1": ["!", "l", "I", "|"],
    "2": ["$", "s", "S", "5"],
    "3": ["€", "E", "e"],
    "4": ["A"],
    "5": ["S", "$", "s", "2"],
    "6": ["G", "g"],
    "7": ["/"],
    "8": ["§", "B", "b"],
    "9": ["P", "p"],
    "0": ["O", "o", "Q", "q"],
}
